### ISSUE TITLE
Request co-maintainer privilage for sync the AUR package

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-noetic-arch/ros-noetic-control-toolbox#2]
https://aur.archlinux.org/packages/ros-noetic-control-toolbox

**Comment by acxz** [comment]
done however please create a PR for review if it is anything more than just a simple version bump

if I don't respond within the day feel free to merge it in yourself

**Comment by acxz** [comment]
Wow that was quick! Thanks so much for helping out with this project, @AchmadFathoni

Even tho I may not show it, I really do appreciate your work!
